name: TEST_CI/CD

on: [push]

jobs: 
  build:
     runs-on: ubuntu-22.04
     steps:
      - name: Build Cat and Grep
        run: |
          cd s21_cat
          make
          cd ../s21_grep
          make
